# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ikran}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["darthdeus"]
  s.date = %q{2010-12-02}
  s.default_executable = %q{ikran}
  s.description = %q{Simple console application for testing HTTP server}
  s.email = %q{darthdeus@gmail.com}
  s.executables = ["ikran"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/ikran",
    "ikran.gemspec",
    "lib/ikran.rb",
    "lib/ikran/reader.rb",
    "spec/ikran_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/darthdeus/ikran}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Simple HTTP console testing framework}
  s.test_files = [
    "spec/ikran_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_runtime_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<cucumber>, [">= 0.6.2"])
      s.add_runtime_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.9.4"])
    else
      s.add_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<cucumber>, [">= 0.6.2"])
      s.add_dependency(%q<addressable>, [">= 2.1.1"])
      s.add_dependency(%q<rspec>, [">= 2.0.0"])
      s.add_dependency(%q<cucumber>, [">= 0.9.4"])
    end
  else
    s.add_dependency(%q<addressable>, [">= 2.1.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<cucumber>, [">= 0.6.2"])
    s.add_dependency(%q<addressable>, [">= 2.1.1"])
    s.add_dependency(%q<rspec>, [">= 2.0.0"])
    s.add_dependency(%q<cucumber>, [">= 0.9.4"])
  end
end

